Repository UCL-ARC/python-tooling, pull requests merged in 2024-09, with the labels that each got.

#445 Add pyfakefs.
  docs/pages/testing.md
Labels: documentation, enhancement

#444 conda → miniforge. Make anaconda explicitly red.
  docs/pages/virtual.md
Labels: bug, documentation

#448 No longer require the second question to be mandatory
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: p4-low
