Repository UCL-ARC/python-tooling, pull requests merged in 2024-06, with the labels that each got.

#377 Revert "Lock file maintenance (#376)"
  docs/Gemfile.lock
Labels: bug, documentation, renovate

#379 Enable `show_submodules` option in MkDocs config
  {{cookiecutter.project_slug}}/mkdocs.yml
Labels: bug, documentation

#378 Run pages build on PRs that touch docs.
  .github/workflows/pages.yml
Labels: documentation

#389 Remove extra bracket
  .all-contributorsrc
Labels: bug

#380 Adding longer prompts for all cookiecutter options
  cookiecutter.json
Labels: documentation, enhancement

#404 Adding further instructions for GitHub pages docs deployment in hook
  hooks/post_gen_project.py
Labels: documentation, enhancement

#358 Open link in new tab
  docs/_config.yml
Labels: enhancement

#407 Automatically generate suggested email from supplied names in template
  cookiecutter.json
Labels: enhancement

#412 Fix `gh repo create` command for the Windows command prompt
  hooks/post_gen_project.py
  tests/test_git_init.py
Labels: bug

#418 Adding tutorial on setting up package using template
  README.md
  docs/pages/templates.md
  tutorial.md
Labels: documentation

#405 Refactor tests
  tests/conftest.py
  tests/test_git_init.py
  tests/test_package_gen.py
  tests/test_package_generation.py
Labels: enhancement, task
