Repository UCL-ARC/python-tooling, pull requests merged in 2024-11, with the labels that each got.

#481 Rework README and move dev instructions to contributing
  .markdownlint.yaml
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement, needs-2-reviewers

#409 Renaming `github_username` to `github_owner` + generating `__repo_name` & `__repo_url`
  cookiecutter.json
  hooks/post_gen_project.py
  tests/test_git_init.py
  tests/test_package_generation.py
  tutorial.md
  {{cookiecutter.project_slug}}/CITATION.cff
  {{cookiecutter.project_slug}}/README.md
  {{cookiecutter.project_slug}}/mkdocs.yml
  {{cookiecutter.project_slug}}/pyproject.toml
Labels: enhancement, needs-2-reviewers

#487 Document that we conform to SPEC0 version support.
  CONTRIBUTING.md
Labels: documentation, task

#473 Two reviewers for "opinionated" changes.
  CONTRIBUTING.md
Labels: documentation, needs-2-reviewers

#475 Add instructions of how to extract the version of the repo
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation, enhancement
