Repository UCL-ARC/python-tooling, pull requests merged in 2024-07, with the labels that each got.

#373 Start a GUI page
  docs/pages/guis.md
Labels: enhancement, website

#428 Create "Recommended libraries" category page with subpages.
  docs/pages/libraries/bindings.md
  docs/pages/libraries/clis.md
  docs/pages/libraries/guis.md
  docs/pages/libraries/index.md
  docs/pages/libraries/jupyter-notebooks.md
  docs/pages/libraries/logging.md
  docs/pages/libraries/parallel-async.md
Labels: documentation, website

#430 Improve expected file test
  tests/test_package_generation.py
Labels: enhancement
