Repository UCL-ARC/python-tooling, pull requests merged in 2024-10, with the labels that each got.

#454 Exclude gnu.org and fsf.org from link checker
  .github/workflows/links.yml
Labels: task

#456 Renovate isn't correctly assigning reviewers
  .renovaterc.json5
Labels: bug, renovate

#460 Native TOML support for `tox`
  .github/workflows/test.yml
  pyproject.toml
  tests/test_package_generation.py
  {{cookiecutter.project_slug}}/.github/workflows/tests.yml
  {{cookiecutter.project_slug}}/pyproject.toml
Labels: enhancement

#465 Add `markdownlint` and tidy up `markdown`
  .markdownlint.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  docs/pages/benchmarking-profiling.md
  docs/pages/ci.md
  docs/pages/community.md
  docs/pages/docs.md
  docs/pages/libraries/bindings.md
  docs/pages/libraries/clis.md
  docs/pages/libraries/guis.md
  docs/pages/libraries/index.md
  docs/pages/libraries/jupyter-notebooks.md
  docs/pages/libraries/logging.md
  docs/pages/libraries/parallel-async.md
  docs/pages/linting.md
  docs/pages/packaging.md
  docs/pages/refactoring.md
  docs/pages/templates.md
  docs/pages/testing.md
  docs/pages/virtual.md
  tests/test_package_generation.py
  tutorial.md
  {{cookiecutter.project_slug}}/.markdownlint.yaml
  {{cookiecutter.project_slug}}/.pre-commit-config.yaml
  {{cookiecutter.project_slug}}/LICENSE.md
  {{cookiecutter.project_slug}}/README.md
  {{cookiecutter.project_slug}}/docs/LICENSE.md
  {{cookiecutter.project_slug}}/docs/index.md
Labels: documentation, enhancement

#464 Add `uv` and `pixi`.
  README.md
  docs/pages/virtual.md
Labels: enhancement, website

#467 Add `hypothesis` for property based testing
  docs/pages/testing.md
Labels: documentation, enhancement

#470 Add release workflow
  .github/workflows/release.yaml
Labels: enhancement

#474 Fix missing `target-version` in `ruff`
  pyproject.toml
Labels: bug

#472 Change to `github.ref_name` for `latest` flag
  .github/workflows/release.yaml
Labels: bug, enhancement, needs-2-reviewers

#478 Missing `--checkout latest` instruction
  README.md
Labels: bug, documentation
