Repository UCL-ARC/python-tooling, pull requests merged in 2024-01, with the labels that each got.

#262 Add issue templates to this project & the template
  .github/ISSUE_TEMPLATES/bug_report.yml
  .github/ISSUE_TEMPLATES/config.yml
  .github/ISSUE_TEMPLATES/documentation.yml
  .github/ISSUE_TEMPLATES/feature_request.yml
  .github/ISSUE_TEMPLATES/question.yml
  .github/ISSUE_TEMPLATES/website.yml
  {{cookiecutter.project_slug}}/.github/ISSUE_TEMPLATES/bug_report.yml
  {{cookiecutter.project_slug}}/.github/ISSUE_TEMPLATES/config.yml
  {{cookiecutter.project_slug}}/.github/ISSUE_TEMPLATES/documentation.yml
  {{cookiecutter.project_slug}}/.github/ISSUE_TEMPLATES/feature_request.yml
  {{cookiecutter.project_slug}}/.github/ISSUE_TEMPLATES/question.yml
Labels: documentation, enhancement

#270 Fix issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/ISSUE_TEMPLATE/website.yml
  {{cookiecutter.project_slug}}/.github/ISSUE_TEMPLATE/bug_report.yml
  {{cookiecutter.project_slug}}/.github/ISSUE_TEMPLATE/config.yml
  {{cookiecutter.project_slug}}/.github/ISSUE_TEMPLATE/documentation.yml
  {{cookiecutter.project_slug}}/.github/ISSUE_TEMPLATE/feature_request.yml
  {{cookiecutter.project_slug}}/.github/ISSUE_TEMPLATE/question.yml
Labels: bug

#276 Update the linters page.
  docs/pages/linting.md
Labels: documentation

#278 Sam's attempt at a welcoming CONTRIBUTING file.
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#247 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#282 Leftovers.
  docs/index.md
  docs/pages/jupyter-notebooks.md
  docs/pages/templates.md
  docs/pages/testing.md
Labels: documentation

#283 Ignore `_version.py` in generated package
  {{cookiecutter.project_slug}}/.gitignore
Labels: bug

#284 Add `importlib` to `pytest`
  pyproject.toml
  {{cookiecutter.project_slug}}/pyproject.toml
Labels: enhancement

#285 Delete IDE table
  docs/pages/dev.md
Labels: documentation

#286 Fix issue template bug report number
  {{cookiecutter.project_slug}}/.github/ISSUE_TEMPLATE/bug_report.yml
  {{cookiecutter.project_slug}}/src/{{cookiecutter.package_name}}/__init__.py
Labels: bug

#293 Top-level LICENSE → LICENSE.md
  LICENSE.md
  {{cookiecutter.project_slug}}/LICENSE.md
Labels: task

#287 Fix linting the template check
  .github/workflows/linting.yml
  .pre-commit-config.yaml
  {{cookiecutter.project_slug}}/LICENSE.md
  {{cookiecutter.project_slug}}/pyproject.toml
  {{cookiecutter.project_slug}}/src/{{cookiecutter.package_name}}/__init__.py
Labels: bug
