Repository UCL-ARC/python-tooling, pull requests merged in 2024-03, with the labels that each got.

#314 Dark mode.
  docs/_config.yml
  docs/_includes/header_custom.html
Labels: enhancement, website

#317 )
  docs/pages/dev.md
Labels: bug, documentation

#320 Always ignore template at top level pre-commit
  .pre-commit-config.yaml
Labels: enhancement

#319 Adding MkDocs docs to template
  cookiecutter.json
  tests/test_package_gen.py
  {{cookiecutter.project_slug}}/.github/workflows/docs.yml
  {{cookiecutter.project_slug}}/README.md
  {{cookiecutter.project_slug}}/docs/LICENSE.md
  {{cookiecutter.project_slug}}/docs/api.md
  {{cookiecutter.project_slug}}/docs/index.md
  {{cookiecutter.project_slug}}/mkdocs.yml
  {{cookiecutter.project_slug}}/pyproject.toml
  {{cookiecutter.project_slug}}/src/{{cookiecutter.package_name}}/__init__.py
Labels: enhancement

#324 Add packaging tips.
  docs/pages/packaging.md
Labels: documentation, enhancement, website

#323 Add a page on parallel and async tools.
  docs/pages/parallel-async.md
Labels: documentation, enhancement, website

#328 Start a utility libraries page.
  docs/pages/utilities.md
Labels: documentation, website

#331 Add asynchronous processing libraries.
  docs/pages/parallel-async.md
Labels: documentation, enhancement, website

#341 Add refactoring.md and tweak virtual environments docs (take 2)
  docs/pages/benchmarking-profiling.md
  docs/pages/refactoring.md
  docs/pages/utilities.md
  docs/pages/virtual.md
Labels: documentation, question, website
