Repository UCL-ARC/python-tooling, pull requests merged in 2025-06, with the labels that each got.

#542 fix: move footer to main layout and improve contrast for WCAG compliance
  .github/workflows/links.yml
  docs/_config.yml
  docs/_includes/components/anchor_icon.html
  docs/_includes/sidebar.html
  docs/_layouts/default.html
  docs/_sass/custom/custom.scss
Labels: enhancement, website, accessibility

#543 Add label to theme-switcher button.
  docs/_includes/header_custom.html
Labels: enhancement, accessibility

#541 Add Vale for content linting to the repo
  .github/workflows/linting.yml
  .gitignore
  .vale.ini
  tutorial.md
Labels: enhancement, needs-2-reviewers

#552 fix: add box shadow instead of outline for all focusable elements and some spacing to the elements
  docs/_includes/header_custom.html
  docs/_sass/custom/custom.scss
  docs/_sass/custom/setup.scss
Labels: enhancement, website, accessibility
