Repository UCL-ARC/python-tooling, pull requests merged in 2025-07, with the labels that each got.

#555 Simplify install instructions
  README.md
Labels: documentation, enhancement

#563 Add FawltyDeps, `deptry` and `pip-check-reqs` as 🟡 good tools.
  docs/pages/linting.md
Labels: documentation, enhancement, needs-2-reviewers

#566 DRY up the test code a bit.
  hooks/post_gen_project.py
  tests/conftest.py
  tests/test_git_init.py
  tests/test_package_generation.py
Labels: enhancement

#585 Switch to `dependency-groups`
  README.md
  tests/data/test_package_generation/pyproject.toml
  tutorial.md
  {{cookiecutter.project_slug}}/pyproject.toml
Labels: enhancement, p4-low, task
